### ISSUE TITLE
nolint directive processing

### ISSUE THREAD

**Issue by nobbynobbs** [butuzov/ireturn#78]
Hi! I have the same problem, as described in [this question on SO](https://stackoverflow.com/q/72385337): when I add `//nolint:ireturn` directive, `nolintlint` start complaining that `//nolint:ireturn` is unused. There is a few workarounds, like `//nolint:all` or `//nolint:nolintlint,ireturn`, or place `nolint://ireturn` directive in inline comment, but its just hacks and not the solve of the problem.

I think that the root of the problem [is here]( https://github.com/butuzov/ireturn/blob/main/analyzer/analyzer.go#L63-L67) and the linter itself shouldn't do anything with `nolint` comment and leave this job for post-processor, like it described in [golangci-lint docs](https://golangci-lint.run/contributing/architecture/)

```sh
golangci-lint version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265 on 2023-11-02T21:40:02Z
```

Minimal reproducible example:

main.go
```go
package main

type tester interface {
	Test()
}

func ireturnError() tester {
	return nil
}

//nolint:ireturn
func nolintlintError() tester {
	return nil
}

//nolint:ireturn,nolintlint
func noError() tester {
	return nil
}

func noError2() tester { //nolint:ireturn
	return nil
}

func main() {
}
```

golangci.yaml
```yaml

linters-settings:
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
linters:
  disable-all: true
  enable:
    - ireturn
    - nolintlint
```
result
```sh
golangci-lint run -c .golangci.yaml
main.go:7:1: ireturnError returns interface (ireturn.com.tester) (ireturn)
func ireturnError() tester {
^
main.go:11:1: directive `//nolint:ireturn` is unused for linter "ireturn" (nolintlint)
//nolint:ireturn
^
```
